FROM node:24-alpine

ENV VITE_AUTHENTICATION_HOST=http://localhost:3001
ENV VITE_CERTIFICATION_HOST=http://localhost:3002

WORKDIR /app

COPY *.json .

RUN npm install

COPY . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "preview", "--", "--host", "--port", "5173"]
